apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app1
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc # CHANGE ME TO WORKLOAD CLUSTER DEV
      - cluster: stage
        url: https://kubernetes.default.svc # CHANGE ME TO WORKLOAD CLUSTER STAGE
      - cluster: prod
        url: https://kubernetes.default.svc # CHANGE ME TO WORKLOAD CLUSTER PROD
  template:
    metadata:
      name: 'app1-{{cluster}}'
    spec:
      project: app1
      source:
        repoURL: https://github.com/jkosik/app1.git
        targetRevision: '{{cluster}}'
        path: '{{cluster}}'
      destination:
        server: '{{url}}'
        namespace: 'app1-{{cluster}}'
      syncPolicy:
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true