# Application owner and Release Manager have to decide about dependency management.
# Dependencies can be
# 1) integral part of app1 Helm charts as Helm dependencies and Helm Subcharts or
# 2) can be deployed as separate external ArgoCD Application (demonstrated by this manifest).

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-dev-dependency1
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: nginx=bitnami/nginx:~1.21
    argocd-image-updater.argoproj.io/nginx.force-update: "true"
    argocd-image-updater.argoproj.io/nginx.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/nginx.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/nginx.update-strategy: name
    argocd-image-updater.argoproj.io/nginx.allow-tags: regexp:^1.21.[0-9]+$
spec:
  project: app1
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 9.4.2
    helm:
      parameters:
        - name: nameOverride
          value: dependency1
        - name: "image.tag"
          value: 1.21.0
    chart: nginx
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: app1-dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
